# Generated by Django 5.1.1 on 2024-09-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_group_character_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
