# Generated by Django 5.1.1 on 2024-09-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_author_mediatype_alter_character_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='off_art',
        ),
        migrations.RemoveField(
            model_name='offart',
            name='media',
        ),
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(default='Описание отсутствует', verbose_name='Описание персонажа'),
        ),
        migrations.AddField(
            model_name='character',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_for_media', to='characters.media', verbose_name='Откуда'),
        ),
        migrations.AddField(
            model_name='offart',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='off_arts', to='characters.mediatype', verbose_name='Откуда'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='character',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='characters.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.TextField(verbose_name='Описание эпизода'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='characters.media', verbose_name='Тип медиа'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.IntegerField(verbose_name='Номер серии'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='release_date',
            field=models.DateField(verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='media',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characters.mediatype', verbose_name='Тип медиа'),
        ),
        migrations.AlterField(
            model_name='media',
            name='release_year',
            field=models.IntegerField(verbose_name='ГГод выпуска'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='offart',
            name='picture',
            field=models.ImageField(upload_to='off_art/', verbose_name='Арт'),
        ),
    ]
