# Generated by Django 5.1.1 on 2024-09-19 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_remove_media_off_art_remove_offart_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='media_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='characters_for_media', to='characters.mediatype', verbose_name='Откуда'),
        ),
    ]
