# Generated by Django 5.1.1 on 2024-09-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_character_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='release_year',
            field=models.DateField(verbose_name='Год выпуска'),
        ),
    ]
