# Generated by Django 5.1.1 on 2024-09-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Caracter',
            new_name='Character',
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
    ]
