# Generated by Django 5.1.1 on 2024-11-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_alter_media_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='picture',
            field=models.ImageField(null=True, upload_to='characters', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='offart',
            name='picture',
            field=models.ImageField(null=True, upload_to='off_arts', verbose_name='Арт'),
        ),
    ]
