# Generated by Django 5.1.3 on 2025-11-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_rename_user_usermine'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='surname',
            field=models.TextField(null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='usermine',
            name='name',
            field=models.TextField(null=True, verbose_name='Имя'),
        ),
    ]
